### ISSUE TITLE
Help Files don't open

### ISSUE THREAD

**Issue by rik-shaw** [wasta-linux/saymore-snap#1]
Help browser opens, the files see available (on the left), but clicking to open doesn't work. I think they would be .chm files??? We may be able to tie into chmsee on Linux somehow (edit a registry file to launch it like we did way back in the old days to have TW5 open the native linux pdf viewer instead of using the windows pdf viewer), or we may just add to wine the appropriate program that reads the chm files.

**Comment by n8marti** [comment]
Yeah, I see the same thing in both the snap installation and a manual one. None of the selections in the Help menu show their content in the main pane. I wonder if it's a problem with the wine web browser? I opened iexplore.exe in the wineprefix and it likewise doesn't show page content at all.

**Comment by n8marti** [comment]
This is due to not including wine-gecko in the installation. This has been fixed as of rev 53.
